baseURL = "https://djdadoo.pilato.fr/"
languageCode = "en"
title = "DJ Elky mixes"
theme = "djelky"
disableKinds = ["taxonomy", "term"]

[mediaTypes]
  [mediaTypes."text/xml"]
    suffixes = ["rss"]

[outputFormats]
  [outputFormats.RSS]
    baseName = "djdadoo"
    mediaType = "text/xml"
    isHTML = false
    isPlainText = true
    noUgly = true

[outputs]
  home    = ["HTML", "RSS"]
  section = ["HTML"]
  page    = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author       = "David Pilato"
  email        = "david@pilato.fr"
  podcastGUID  = "5e560267-5f32-55d3-b370-8f66f80ddb8f"
  podcastImage = "djdadoo-new.jpg"
  subtitle     = "Just playing with my DJ gears, from DDJ-T1 to CDJ3000"
  description  = "If you love funk, house and DJ groove sound, you will like those mixes. Enjoy!"
  itunesLink   = "https://podcasts.apple.com/fr/podcast/dj-elky-mixes/id542004633"
